# Generated by Django 2.2.13 on 2020-08-12 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=20, verbose_name='父亲名')),
            ],
        ),
        migrations.CreateModel(
            name='Son',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('son_name', models.CharField(max_length=20, verbose_name='儿子名')),
                ('father', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oto.Father')),
            ],
        ),
    ]
