# Generated by Django 2.2.13 on 2020-08-12 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='father',
            old_name='father_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='son',
            old_name='son_name',
            new_name='name',
        ),
    ]
