# Generated by Django 2.2.13 on 2020-08-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oto', '0002_auto_20200812_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='father',
            options={'verbose_name': '父亲', 'verbose_name_plural': '父亲'},
        ),
        migrations.AlterModelOptions(
            name='son',
            options={'verbose_name': '儿子', 'verbose_name_plural': '儿子'},
        ),
    ]
