# Generated by Django 2.2.13 on 2020-08-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20200808_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.CharField(max_length=50, verbose_name='出版社'),
        ),
    ]
