# Generated by Django 2.2.13 on 2020-08-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20200808_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='market_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='市场价'),
        ),
    ]
