# Generated by Django 2.2.13 on 2020-08-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20200808_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='test',
            field=models.CharField(default='', max_length=50, verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='book',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='市场价'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.CharField(default='', max_length=50, verbose_name='出版社'),
        ),
    ]
