# Generated by Django 2.2.13 on 2020-08-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20200808_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='test',
        ),
    ]
