# Generated by Django 2.2.13 on 2020-08-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_remove_book_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='note',
            field=models.TextField(default='', max_length=1000, verbose_name='备注'),
        ),
    ]
