# Generated by Django 2.2.13 on 2020-08-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '图书', 'verbose_name_plural': '图书'},
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
